---

- name: Ensure the tftp and tftp-server packages
  ansible.builtin.package:
    name:
      - tftp
      - tftp-server
    state: present
  become: true

- name: Ensure group exists
  ansible.builtin.group:
    name: tftpd
    system: true
    local: true
    state: present
  become: true

- name: Ensure tftpd user exists
  ansible.builtin.user:
    name: tftpd
    group: tftpd
    home: /var/lib/tftpboot
    comment: TFTP service account
    create_home: false
    password: "!"
    password_lock: true
    shell: /sbin/nologin
    system: true
    local: true
    state: present
  become: true

- name: Create tftpboot home
  ansible.builtin.file:
    path: /var/lib/tftpboot
    state: directory
    # Note the sticky group bit
    mode: '02775'
    owner: tftpd
    group: tftpd
  become: true

- name: Make sure {{ config_destination }} exists
  ansible.builtin.file:
    name: "{{ config_destination }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Override default TFTP server options
  ansible.builtin.template:
    src: override.conf.j2
    dest: "{{ config_destination }}/override.conf"
    mode: '0644'
  become: true

- name: Enable TFTP activation socket
  ansible.builtin.systemd:
    name: tftp.socket
    enabled: true
    state: started
  become: true

- name: Allow TFTP server to read its home directory
  when: ansible_facts.selinux.status in ['enforcing', 'permissive']
  seboolean:
    name: tftp_home_dir
    state: true
    persistent: true
  become: true

- name: Enable firewall for TFTP
  firewalld:
    zone: internal
    service: tftp
    permanent: true
    immediate: true
    state: enabled
  become: true

...
