#!/usr/bin/env ansible-playbook
---
# Run after license has been entered.
- name: Configure AAP
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    awx_host: "{{ groups.automationcontroller[0] }}"
    # yamllint disable-line rule:line-length
    cfg: "-k --conf.host https://{{ awx_host }} --conf.user {{ awx_user | default('admin', true) }}"

  pre_tasks:
    - name: Install collections
      changed_when: true
      # yamllint disable-line rule:line-length
      ansible.builtin.command: "ansible-galaxy collection install -f -p collections -r collections/requirements.yml"

    - name: Login to Tower
      no_log: false
      changed_when: false
      ansible.builtin.command: "awx {{ cfg }} --conf.password {{ admin_password }} -k login"
      register: awx_login

    - name: Set awx_token
      ansible.builtin.set_fact:
        awx_token: "{{ awx_login.stdout | from_json | json_query('token') }}"

    - name: Create ~/.tower_cli.cfg
      ansible.builtin.template:
        src: tower_cli.cfg
        dest: "~/.tower_cli.cfg"
        mode: 0600
