#!/usr/bin/env ansible-playbook
---

- name: Provision RHEL8 VM
  hosts: all:!localhost
  become: true
  gather_facts: true
  collections: community.general

  vars_files:
    - stig-vars.yml

  roles:
    - dvd_repository
 #   - apache
 #   - tftpd
 #   - kickstart
    - chrony
    - rhel8_fixes
#    - role: RHEL8-STIG
...
