#!/usr/bin/env ansible-playbook
---

- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars_files:
    - configs/controller_auth.yml
  collections:
    - awx.awx
    - redhat_cop.controller_configuration

  pre_tasks:

    - name: Wait for Controller to come up
      ansible.builtin.uri:
        url: "https://{{ controller_hostname }}/api/v2/ping"
        status_code: 200
        validate_certs: "{{ controller_validate_certs }}"
      register: result
      until: result.status == 200
      retries: 20
      delay: 30
      ignore_errors: true

    - name: Sleep for 10 seconds and allow awx to come up.
      ansible.builtin.wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: ./configs
        ignore_files: [controller_auth.yml]
        extensions: ["yml"]
      tags:
        - always

  roles:
    - dispatch  # The dispatch role calls all of the other roles.
