#!/usr/bin/env ansible-playbook
---

- name: Provision RHEL8 VM
  hosts: all:!localhost
  become: true
  gather_facts: true

  roles:
    - dvd_repository
    - grace_period

- name: Provision AAP
  hosts: server01,server02
  become: true
  gather_facts: true

  roles:
    - role: ssh_keys
      tags: ssh_keys
    - role: aap
      tags: aap

