#!/usr/bin/env ansible-playbook
---

- name: Provision RHEL8 VM
  hosts: all:!localhost
  become: true
  gather_facts: true

  roles:
    - dvd_repository

- name: Provision AAP
  hosts: server01,server02
  become: true
  gather_facts: true

  tasks:
    - ansible.builtin.include_role:
        name: chrony
    - ansible.builtin.include_role:
        name: ssh_keys
    - ansible.builtin.include_role:
        name: grace_period
        tasks_from: present
    - ansible.builtin.include_role:
        name: aap
    - ansible.builtin.include_role:
        name: grace_period
        tasks_from: absent
    - ansible.builtin.include_role:
        name: rhel8_fixes
