---
controller_inventory_sources:
  - name: Controller
    source: scm
    source_project: Controller
    source_path: inventory
    inventory: Controller
    credential: Vagrant
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
