---
controller_configuration_project_update_async_retries: 180
controller_settings:
  settings:
    AWX_ISOLATION_BASE_PATH: /var/tmp
    AWX_COLLECTIONS_ENABLED: true
    AWX_ROLES_ENABLED: true
    ORG_ADMINS_CAN_SEE_ALL_USERS: true
    MANAGE_ORGANIZATION_AUTH: false
    AD_HOC_COMMANDS:
      - ping
      - setup
