---

- name: Restart fapolicyd
  ansible.builtin.systemd:
    name: fapolicyd
    state: restarted
    enabled: true

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true
