---
# grace_period
tmp_mounts:
  - { src: /dev/mapper/vgsys-lv_tmp, path: /tmp }
  - { src: /dev/mapper/vgsys-lv_vartmp, path: /var/tmp }
# nettime
net_allow: []

primary_machine: "{{ groups.automationcontroller[0] }}"
secondary_machine: "{{ groups.automationhub[0] }}"
registry_url: 192.168.56.12.nip.io
tower_validate_certs: false
