---
- name: Keep permissive mode in fapolicy
  ansible.builtin.lineinfile:
    dest: /etc/fapolicyd/fapolicyd.conf
    line: "permissive = 1"
    state: present
    regexp: '^permissive'
  notify:
    - Restart fapolicyd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
