---
- name: Relax fapolicy for installation
  ansible.builtin.lineinfile:
    dest: /etc/fapolicyd/fapolicyd.conf
    line: "permissive = 1"
    state: present
    regexp: '^permissive'
  notify:
    - Restart fapolicyd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Relax mount options
  ansible.builtin.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: xfs
    state: mounted
    opts: 'rw,nodev,nosuid'
  loop: "{{ tmp_mounts }}"

- name: Manage local tmp directory
  become: true
  ansible.builtin.file:
    path: /usr/local/tmp/
    owner: root
    group: root
    state: directory
    mode: 01777

- name: Manage ansible tmp directory
  become: true
  ansible.builtin.file:
    path: /usr/local/tmp/ansible
    owner: "{{ ansible_user }}"
    state: directory
    mode: 01750
