---
- name: Ensure ssh directory
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 700

- name: Install private key
  become: true
  ansible.builtin.copy:
    src: "{{ private_key }}"
    dest: /root/.ssh/id_rsa
    mode: 0600

- name: Setup .ssh/config
  become: true
  ansible.builtin.template:
    src: config
    dest: /root/.ssh/config
    mode: 0600

- name: Generate known host records
  become: true
  ansible.builtin.shell: ssh-keyscan -H {{ primary_machine }} {{ secondary_machine }} > /root/.ssh/known_hosts
  changed_when: true
