---

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true
    daemon_reload: true
    masked: false

- name: Enable usbguard
  ansible.builtin.systemd:
    name: usbguard
    enabled: true
    state: started
    masked: false
