---
controller_settings:
  settings:
    AWX_ISOLATION_BASE_PATH: /usr/local/tmp
    ORG_ADMINS_CAN_SEE_ALL_USERS: true
    MANAGE_ORGANIZATION_AUTH: false
    AD_HOC_COMMANDS:
      - ping
      - setup
